function p_ee = FK_fun(in1,in2)
%FK_fun
%    P_EE = FK_fun(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    05-Apr-2026 13:08:36

a0 = in2(1,:);
a1 = in2(3,:);
a2 = in2(5,:);
d1 = in2(2,:);
d2 = in2(4,:);
ell_e = in2(6,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q2);
t5 = q2+q3;
t6 = a1.*t3;
t7 = cos(t5);
t8 = d2.*t4;
t9 = q4+t5;
t10 = sin(t5);
p_ee = [a0+t2.*(t6+t8)+a2.*t2.*t3.*cos(q3)+ell_e.*t2.*t7.*cos(q4)-a2.*t2.*t4.*sin(q3)-ell_e.*t2.*t10.*sin(q4);sin(q1).*(t6+t8+a2.*t7+ell_e.*cos(t9));d1-a1.*t4-a2.*t10+d2.*t3-ell_e.*sin(t9)];
end
