function G_full = G_fun(in1,in2)
%G_fun
%    G_full = G_fun(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    05-Apr-2026 13:08:36

a1 = in2(3,:);
a2 = in2(5,:);
d2 = in2(4,:);
ell_e = in2(6,:);
g = in2(23,:);
m1 = in2(7,:);
m2 = in2(8,:);
m3 = in2(9,:);
m4 = in2(10,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = cos(q2);
t3 = sin(q2);
t4 = q2+q3;
t5 = a1.*t2;
t6 = cos(t4);
t7 = d2.*t3;
t8 = q4+t4;
t9 = cos(t8);
t10 = a2.*t6;
t11 = ell_e.*t9;
t12 = t11./2.0;
G_full = [0.0;-g.*m1.*(t5./2.0+t7./2.0)-g.*m2.*(t5+t7+t10./2.0)-g.*m3.*(t5+t7+t10+t12)-g.*m4.*(t5+t7+t10+t11);-g.*m3.*(t10+t12)-g.*m4.*(t10+t11)-(g.*m2.*t10)./2.0;g.*t11.*(m3+m4.*2.0).*(-1.0./2.0)];
end
